{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError"]]},"abstract":[{"type":"text","text":"Could not connect to server, or server did not respond before timeout."}],"variants":[{"paths":["\/documentation\/identityorchestration\/tsidojourneyerror\/networkerror"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/networkError","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"symbolKind":"case","externalID":"s:21IdentityOrchestration17TSIdoJourneyErrorO07networkE0yA2CmF","role":"symbol","modules":[{"name":"IdentityOrchestration"}],"title":"TSIdoJourneyError.networkError"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration":{"title":"IdentityOrchestration","kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","role":"collection","abstract":[],"url":"\/documentation\/identityorchestration"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError/networkError":{"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/networkError","url":"\/documentation\/identityorchestration\/tsidojourneyerror\/networkerror","abstract":[{"type":"text","text":"Could not connect to server, or server did not respond before timeout."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"}],"type":"topic","kind":"symbol","title":"TSIdoJourneyError.networkError"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError":{"kind":"symbol","url":"\/documentation\/identityorchestration\/tsidojourneyerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSIdoJourneyError","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The enum for the start Journey errors."}],"title":"TSIdoJourneyError","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError","navigatorTitle":[{"text":"TSIdoJourneyError","kind":"identifier"}]}}}