{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityorchestration\/tsidojourneyerror\/servererror(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/serverError(_:)"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError"]]},"abstract":[{"text":"The server returned an unexpected error.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"symbolKind":"case","externalID":"s:21IdentityOrchestration17TSIdoJourneyErrorO06serverE0yACs0E0_pSgcACmF","roleHeading":"Case","role":"symbol","modules":[{"name":"IdentityOrchestration"}],"title":"TSIdoJourneyError.serverError(_:)"},"kind":"symbol","references":{"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError/serverError(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"url":"\/documentation\/identityorchestration\/tsidojourneyerror\/servererror(_:)","abstract":[{"text":"The server returned an unexpected error.","type":"text"}],"role":"symbol","type":"topic","title":"TSIdoJourneyError.serverError(_:)","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/serverError(_:)","kind":"symbol"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError","title":"TSIdoJourneyError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSIdoJourneyError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TSIdoJourneyError"}],"abstract":[{"type":"text","text":"The enum for the start Journey errors."}],"role":"symbol","type":"topic","url":"\/documentation\/identityorchestration\/tsidojourneyerror","kind":"symbol"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration":{"abstract":[],"kind":"symbol","title":"IdentityOrchestration","url":"\/documentation\/identityorchestration","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","role":"collection"}}}